scigene_vis_field:
  fieldID:
    - 159384605 # Music visualization
    - 36464697  # Visualization
    - 4379982   # Software visualization
    - 83893533  # Flow visualization

scigene_visualization_field:
  fieldID:
    - 159384605 # Music visualization
    - 36464697  # Visualization
    - 4379982   # Software visualization
    - 83893533  # Flow visualization
    - 59732488  # Visual analytics
  children:     # search the direct children of the fieldID
    - 36464697  # Visualization
  JournalID:
    - 10355277
    - 84775595
    - 2898150413
    - 67831204
    - 55152591
  ConferenceID:
    - 2757964222
    - 2754539197
    - 2754685548
    - 1161805661
    - 1200770042
    - 2537178404
    - 1200145187
    - 2754213367
    - 1168254271
    - 2625874324
    - 2759977425
    - 1191926394
    - 2898476843
    - 1148385487
    - 2625527217


scigene_database_field:
  fieldID: 
    - 77088390    # Database
    - 2522767166  # Data science: 524553
  JournalID:
    - 90119964
    - 30698027
    - 78926909
    - 112141509
    - 136993123
    - 174847851
    - 192650101
    - 193006928
  ConferenceID:
    - 1168542559
    - 1175089206
    - 1163988186
    - 1133523790
    - 1194094125
    - 1120384002
    - 1184699546
    - 1165285842
    - 1201561728
    - 1192664773
    - 1176514135
    - 1134031032
    - 1156109491


scigene_VCG_field:
  fieldID:
    - 159384605 # Music visualization
    - 36464697  # Visualization
    - 4379982   # Software visualization
    - 83893533  # Flow visualization
    - 59732488  # Visual analytics
    - 121684516 # Computer graphics (images) 
  children:     # search the direct children of the fieldID
    - 36464697  # Visualization
  JournalID:
    - 10355277  # VIS
    - 84775595
    - 2898150413
    - 67831204
    - 55152591
    - 185367456 # CG
    - 135221619
    - 67831204
    - 17421805
    - 2898187931
    - 2898124066
  ConferenceID:
    - 2757964222  # VIS
    - 2754539197
    - 2754685548
    - 1161805661
    - 1200770042
    - 2537178404
    - 1200145187
    - 2754213367
    - 1168254271
    - 2625874324
    - 2759977425
    - 1191926394
    - 2898476843
    - 1148385487
    - 2625527217
    - 1164321581  # CG
    - 1165838108
    - 2758845705
    - 2754362256
    - 1132689015
    - 1200430907
    - 1140059087
    - 2626018664

scigene_physics_field:
  fieldID: 121332964

scigene_CG_field:
  fieldID:
    - 121684516 # Computer graphics (images) 
  JournalID:
    - 84775595  # ieee transactions on visualization and computer graphics
    - 67831204  # computer graphics forum
    - 185367456 # CG
    - 135221619
    - 67831204
    - 17421805
    - 2898187931
    - 2898124066
  ConferenceID:
    - 1164321581  # CG
    - 1165838108
    - 2758845705
    - 2754362256
    - 1132689015
    - 1200430907
    - 1140059087
    - 2626018664


scigene_AI_field:
  field:
    - Information retrieval
    - Speech recognition
    - Computer vision
    - Multimedia
    - Knowledge management
    - Machine learning
    - Data mining
    - World Wide web
    - Artificial intelligence
    - Pattern recognition
    - Natural language processing
    - Data science

scigene_AIChild_field:
  field:
    - Information retrieval
    - Speech recognition
    - Computer vision
    - Multimedia
    - Knowledge management
    - Machine learning
    - Data mining
    - World Wide web
    - Artificial intelligence
    - Pattern recognition
    - Natural language processing
    - Data science
  children:
    - Information retrieval
    - Speech recognition
    - Computer vision
    - Multimedia
    - Knowledge management
    - Machine learning
    - Data mining
    - World Wide web
    - Artificial intelligence
    - Pattern recognition
    - Natural language processing
    - Data science
